---
- name: general stuff to install
  hosts: all
  remote_user: sudo
  become: true
  tasks:
  - name: get update
    apt:
      upgrade: yes
      update_cache: yes
  - name: install pip
    shell: sudo apt-get install python3-pip -y

  - name: install oracle
    shell: sudo apt-get install openjdk-8-jre-headless -y

  - name: public key
    shell: sudo cat /vagrant/environment/jenkin_key.pub >> /home/vagrant/.ssh/authorized_keys

  - name: install git
    shell: sudo apt-get install git -y
